## Write a Numpy program to compute the multiplication of two given matrixes

#### Numpy program to compute the multiplication of two given matrixes

In [7]:
####Numpy program to compute the multiplication of two given matrixes
import numpy as np
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
print("original matrix:")
print(p)
print(q)
result1 = np.dot(p, q)
print("Result of the said matrix multiplication:")
print(result1)



original matrix:
[[1, 0], [0, 1]]
[[1, 2], [3, 4]]
Result of the said matrix multiplication:
[[1 2]
 [3 4]]


## Write a NumPy program to compute the determinant of a given square array

In [8]:
####NumPy program to compute the determinant of a given square array
import numpy as np
from numpy import linalg as LA
a = np.array([[1, 0], [1, 2]])
print("Original 2-d array")
print(a)
print("Determinant of the said 2-D array:")
print(np.linalg.det(a))

Original 2-d array
[[1 0]
 [1 2]]
Determinant of the said 2-D array:
2.0


## Write a NumPy program to compute the cross product of two given vectors

In [10]:
###a NumPy program to compute the cross product of two given vectors.
import numpy as np
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
print("original matrix:")
print(p)
print(q)
result1 = np.cross(p, q)
result2 = np.cross(q, p)
print("cross product of the said two vectors(p, q):")
print(result1)
print("cross product of the said two vectors(q, p):")
print(result2)


original matrix:
[[1, 0], [0, 1]]
[[1, 2], [3, 4]]
cross product of the said two vectors(p, q):
[ 2 -3]
cross product of the said two vectors(q, p):
[-2  3]


## Write a NumPy program to compute the condition number of a given matrix

In [11]:
### a NumPy program to compute the condition number of a given matrix.
import numpy as np
from numpy import linalg as LA
a = np.array([[1, 0, -1], [0, 1, 0], [1, 0, 1]])
print("Original matrix:")
print(a)
print("The condition number of the said matrix:")
print(LA.cond(a))


Original matrix:
[[ 1  0 -1]
 [ 0  1  0]
 [ 1  0  1]]
The condition number of the said matrix:
1.4142135623730951


## Write a NumPy program to compute the inverse of a given matrix

In [12]:
#a NumPy program to compute the inverse of a given matrix.
import numpy as np
m = np.array([[1,2],[3,4]])
print("Original matrix:")
print(m)
result =  np.linalg.inv(m)
print("Inverse of the said matrix:")
print(result)


Original matrix:
[[1 2]
 [3 4]]
Inverse of the said matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]
